# Generated by Django 5.2 on 2025-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_github_remove_resume_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
